version: '3.8'

services:
  onix-db:
    image: mysql:8.0
    container_name: onix-db
    restart: always
    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: onix_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci